version: 1.0.{build}
image: Visual Studio 2017
branches:
  except:
  - master
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
services: mssql2017
install:
- cmd: dotnet restore src/Students.sln
build:
  project: src/Students.sln
  verbosity: minimal